CREATE TABLE business (
        _id VARCHAR(24),
        id VARCHAR(22),
        alias VARCHAR(100),
        name VARCHAR(100),
        image_url VARCHAR(200),
        is_closed BIT,
        url VARCHAR(200),
        review_count INT,
        categories VARCHAR(50),
        rating INT,
        transactions VARCHAR(50),
        price VARCHAR(10),
        phone VARCHAR(20),
        display_phone VARCHAR(20),
        distance DECIMAL(18, 10),
        latitude DECIMAL(9, 6),
        longitude DECIMAL(9, 6),
        address1 VARCHAR(100),
        address2 VARCHAR(100),
        address3 VARCHAR(100),
        city VARCHAR(50),
        zip_code VARCHAR(10),
        country VARCHAR(50),
        state VARCHAR(50),
        display_address VARCHAR(50)
    )